server:
  port: 8081

spring:
  datasource:
    username: root
    password: wxh564738
    url: jdbc:mysql://10.211.55.7/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource



  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 10.211.55.7

logging:
  level:
    com.wuxinhua.mapper.*.xml: debug
